# Generated by Django 4.1.5 on 2023-01-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=50)),
                ("movie_genres", models.CharField(max_length=50)),
                ("char_cast", models.CharField(max_length=50)),
                ("overview", models.CharField(max_length=50)),
                ("tag_line", models.CharField(max_length=50)),
            ],
        ),
    ]
